### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Albertolona** [Nightinggale/Religion_and_Revolution_Extended#1]
Dear Nightinggale

Is this mod now incorporated into the official RaR?

If so, is there any chance of a release of a more recent build?

The stable 2.7 Rar is the latest release has been out for about a year and it is a bit broken.

I would really appreciate if you could help to release a more recent build so I can play this fantastic mod again.

Many thanks.

**Comment by Nightinggale** [comment]
This port was merged into RaR 5 years ago and I'm active on RaR, not RaRE. I would recommend posting on the RaR forum if you want to be read by anybody related to RaR.
